spring.config.activate.on-profile=default

spring.datasource.url=${JDBC_URL_DEV}
spring.datasource.username=${JDBC_USER}
spring.datasource.password=${JDBC_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
